import './globals.css'
import { Roboto } from 'next/font/google'
import Navebar from '@/components/navebar/Navebar'

const inter = Roboto({ subsets: ['latin'],
weight: ['100', '300', '400','500', '700', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  )
}
